In [2]:
import keras

In [44]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import SGD,Adam,RMSprop

In [15]:
import numpy as np
from numpy.random import random

In [11]:
print(keras.__version__)

2.1.6


In [12]:
model = Sequential()

In [13]:
model.add(Dense(1, input_shape=(2,)))

In [51]:
model.compile(optimizer=Adam(lr=0.01), loss='mse')

In [78]:
x1 = random((3000,2))
x2 = random((3000,2))
x1[:5],x2[:5]

(array([[0.40846436, 0.376415  ],
        [0.12113353, 0.66530565],
        [0.20460729, 0.64719812],
        [0.90161676, 0.56960876],
        [0.92563018, 0.0851898 ]]), array([[0.5368978 , 0.13715436],
        [0.0630466 , 0.43500133],
        [0.1183156 , 0.01716471],
        [0.64493956, 0.80337877],
        [0.49693414, 0.43808538]]))

In [79]:
y1 = np.dot(x1, [2, 3]) + 1
y2 = np.dot(x2, [2, 3]) + 1
y1[:5],y2[:5]

(array([2.94617371, 3.23818402, 3.35080894, 4.51205981, 3.10682977]),
 array([2.48525868, 2.4310972 , 1.28812532, 4.70001544, 3.30812441]))

In [54]:
model.fit(x, y, epochs=100)

Epoch 1/100
3000/3000 [==============================] - 0s 77us/step - loss: 7.9515e-06
Epoch 2/100
3000/3000 [==============================] - 0s 36us/step - loss: 4.7783e-10
Epoch 3/100
3000/3000 [==============================] - 0s 37us/step - loss: 9.1722e-14
Epoch 4/100
3000/3000 [==============================] - 0s 36us/step - loss: 2.5196e-14
Epoch 5/100
3000/3000 [==============================] - 0s 35us/step - loss: 4.2325e-14
Epoch 6/100
3000/3000 [==============================] - 0s 35us/step - loss: 1.5485e-13
Epoch 7/100
3000/3000 [==============================] - 0s 35us/step - loss: 1.4372e-13
Epoch 8/100
3000/3000 [==============================] - 0s 34us/step - loss: 2.3624e-13
Epoch 9/100
3000/3000 [==============================] - 0s 35us/step - loss: 2.7660e-13
Epoch 10/100
3000/3000 [==============================] - 0s 35us/step - loss: 2.1132e-13
Epoch 11/100
3000/3000 [==============================] - 0s 35us/step - loss: 4.0097e-12
Epoch 12/100
3000/3

3000/3000 [==============================] - 0s 35us/step - loss: 4.2584e-06
Epoch 93/100
3000/3000 [==============================] - 0s 36us/step - loss: 6.8354e-08
Epoch 94/100
3000/3000 [==============================] - 0s 37us/step - loss: 2.3574e-11
Epoch 95/100
3000/3000 [==============================] - 0s 35us/step - loss: 7.5036e-13
Epoch 96/100
3000/3000 [==============================] - 0s 35us/step - loss: 3.5533e-13
Epoch 97/100
3000/3000 [==============================] - 0s 36us/step - loss: 9.6895e-13
Epoch 98/100
3000/3000 [==============================] - 0s 35us/step - loss: 5.9571e-13
Epoch 99/100
3000/3000 [==============================] - 0s 36us/step - loss: 2.7514e-12
Epoch 100/100
3000/3000 [==============================] - 0s 35us/step - loss: 4.5053e-11


In [82]:
model.train_on_batch([x1,x2],[y1,y2])

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[0.40846436, 0.376415  ],
       [0.12113353, 0.66530565],
       [0.20460729, 0.64719812],
       ...,
       [0.47878298, 0.8168337 ],
       [0.78257819, 0.48675111],
       [0.21484949, 0....

In [55]:
model.get_weights()

[array([[2.000012],
        [3.000013]], dtype=float32), array([1.0000148], dtype=float32)]

In [31]:
model.get_config()

[{'class_name': 'Dense',
  'config': {'activation': 'linear',
   'activity_regularizer': None,
   'batch_input_shape': (None, 2),
   'bias_constraint': None,
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'bias_regularizer': None,
   'dtype': 'float32',
   'kernel_constraint': None,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'distribution': 'uniform',
     'mode': 'fan_avg',
     'scale': 1.0,
     'seed': None}},
   'kernel_regularizer': None,
   'name': 'dense_3',
   'trainable': True,
   'units': 1,
   'use_bias': True}}]

In [32]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [70]:
x=random((1,2))
print(x)
type(x)

[[0.51427027 0.52455614]]


numpy.ndarray

In [74]:
model.predict(np.array([[1,2]]))

array([[9.000053]], dtype=float32)

In [66]:
print(np.dot(x, [2,3])+1)

[3.7073007]
